version: "3"
services:
  web_app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:5173"
    volumes:
      - /app/node_modules
      - .:/app
  build_app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["npm", "run", "build"]
